# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_AppMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 936)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/images/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(88, 88, 88);\n"
"color: rgb(247, 247, 247);")
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowNestedDocks|QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startlineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.startlineEdit.setMinimumSize(QtCore.QSize(0, 45))
        self.startlineEdit.setStyleSheet("border-radius:7px;\n"
"border:none;\n"
"border-bottom:2px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.38806 rgba(255, 170, 0, 255), stop:1 rgba(0, 0, 0, 255));\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.626866 rgba(255, 232, 185, 255));\n"
"color: rgb(0, 0, 0);")
        self.startlineEdit.setText("")
        self.startlineEdit.setObjectName("startlineEdit")
        self.horizontalLayout.addWidget(self.startlineEdit)
        self.endlineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.endlineEdit.setMinimumSize(QtCore.QSize(0, 45))
        self.endlineEdit.setStyleSheet("border-radius:7px;\n"
"border:none;\n"
"border-bottom:2px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.38806 rgba(255, 170, 0, 255), stop:1 rgba(0, 0, 0, 255));\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.626866 rgba(255, 232, 185, 255));\n"
"color: rgb(0, 0, 0);")
        self.endlineEdit.setObjectName("endlineEdit")
        self.horizontalLayout.addWidget(self.endlineEdit)
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchButton.sizePolicy().hasHeightForWidth())
        self.searchButton.setSizePolicy(sizePolicy)
        self.searchButton.setMinimumSize(QtCore.QSize(100, 45))
        self.searchButton.setMaximumSize(QtCore.QSize(170, 45))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.searchButton.setFont(font)
        self.searchButton.setStyleSheet("QPushButton{\n"
"    border-radius: 7px;\n"
"    background-color: rgb(0, 0, 0);\n"
"    border: 2px solid   rgb(236, 236, 236);\n"
"    color: rgb(255, 170, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    border: 4px double rgb(255, 170, 0);\n"
"    color: rgb(255, 170, 0)\n"
"}\n"
"QPushButton:checked{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color:  rgb(255, 170, 0);\n"
"    \n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}\n"
"")
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout.addWidget(self.searchButton)
        self.verticalLayout_9.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabWidget{border:none;color: rgb(0, 0, 0);}\n"
"\n"
"\n"
"QTabBar::tab:unselected\n"
"{\n"
"    color:rgb(255, 255, 255);\n"
"    /*background:transparent;*/\n"
"    width:60px;\n"
"    \n"
"    font-family:\"微软雅黑\";\n"
"    font-size:14px;\n"
"    border-bottom:0.1px solid rgb(220, 220, 220);\n"
"\n"
"}\n"
"\n"
"QTabBar::tab:selected\n"
"{\n"
"    color:rgb(255, 170, 0);\n"
"    width:60px;\n"
"    /*background:transparent;*/\n"
"    \n"
"    font-family:\"微软雅黑\";\n"
"    font-size:17px;\n"
"    border-bottom:4px solid rgb(188, 125, 0);\n"
"\n"
"}\n"
"QTabBar::tab{min-width:80px}\n"
" \n"
"\n"
"\n"
"\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_mapCanvas = QtWidgets.QWidget()
        self.tab_mapCanvas.setObjectName("tab_mapCanvas")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_mapCanvas)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tabWidget.addTab(self.tab_mapCanvas, "")
        self.tab_folium = QtWidgets.QWidget()
        self.tab_folium.setObjectName("tab_folium")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_folium)
        self.verticalLayout.setObjectName("verticalLayout")
        self.webEngineView = QtWebEngineWidgets.QWebEngineView(self.tab_folium)
        self.webEngineView.setProperty("url", QtCore.QUrl("about:blank"))
        self.webEngineView.setObjectName("webEngineView")
        self.verticalLayout.addWidget(self.webEngineView)
        self.tabWidget.addTab(self.tab_folium, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout_9.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.dockWidget_feature = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_feature.setMinimumSize(QtCore.QSize(400, 300))
        self.dockWidget_feature.setStyleSheet("QDockWidget{background-color: rgb(79, 79, 79);border-radius:20px;color: rgb(218, 218, 218);}\n"
"QLabel{color: rgb(218, 218, 218);}\n"
"\n"
"\n"
"QPushButton{\n"
"    border-radius: 7px;\n"
"    background-color: rgb(0, 0, 0);\n"
"    border: 2px solid  rgb(236, 236, 236);\n"
"    color: rgb(255, 170, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    border: 4px double rgb(255, 170, 0);\n"
"    color: rgb(255, 170, 0)\n"
"}\n"
"QPushButton:checked{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color:  rgb(255, 170, 0);\n"
"    \n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.dockWidget_feature.setObjectName("dockWidget_feature")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea = QtWidgets.QScrollArea(self.dockWidgetContents_2)
        self.scrollArea.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:20px;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 519, 1000))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.feat_name_D1 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.feat_name_D1.setStyleSheet("font: 16pt \"黑体\";")
        self.feat_name_D1.setObjectName("feat_name_D1")
        self.horizontalLayout_11.addWidget(self.feat_name_D1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.checkBox = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.checkBox.setMaximumSize(QtCore.QSize(107, 35))
        self.checkBox.setText("")
        self.checkBox.setPixmap(QtGui.QPixmap(":/image/images/未标记.png"))
        self.checkBox.setScaledContents(True)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_11.addWidget(self.checkBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_15.addWidget(self.label_7)
        self.posilineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.posilineEdit.setStyleSheet("color: rgb(255, 255, 255);")
        self.posilineEdit.setObjectName("posilineEdit")
        self.horizontalLayout_15.addWidget(self.posilineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem1)
        self.btn_addPoint = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.btn_addPoint.setMinimumSize(QtCore.QSize(107, 35))
        self.btn_addPoint.setMaximumSize(QtCore.QSize(107, 35))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_addPoint.setFont(font)
        self.btn_addPoint.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.626866 rgba(255, 232, 185, 255));\n"
"color: rgb(44, 44, 44);\n"
"border-radius:7px")
        self.btn_addPoint.setObjectName("btn_addPoint")
        self.horizontalLayout_15.addWidget(self.btn_addPoint)
        self.horizontalLayout_15.setStretch(1, 4)
        self.horizontalLayout_15.setStretch(2, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.timelineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.timelineEdit.setObjectName("timelineEdit")
        self.horizontalLayout_3.addWidget(self.timelineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.btn_update = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.btn_update.setMinimumSize(QtCore.QSize(107, 35))
        self.btn_update.setMaximumSize(QtCore.QSize(107, 35))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_update.setFont(font)
        self.btn_update.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.626866 rgba(255, 232, 185, 255));\n"
"color: rgb(44, 44, 44);\n"
"border-radius:7px")
        self.btn_update.setObjectName("btn_update")
        self.horizontalLayout_3.addWidget(self.btn_update)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(149, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.btn_routeGuide = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.btn_routeGuide.setMinimumSize(QtCore.QSize(170, 35))
        self.btn_routeGuide.setMaximumSize(QtCore.QSize(170, 35))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_routeGuide.setFont(font)
        self.btn_routeGuide.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color:rgb(255, 170, 0);\n"
"border-radius:7px")
        self.btn_routeGuide.setObjectName("btn_routeGuide")
        self.horizontalLayout_5.addWidget(self.btn_routeGuide)
        spacerItem4 = QtWidgets.QSpacerItem(149, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.feat_showText = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.feat_showText.setMinimumSize(QtCore.QSize(0, 150))
        self.feat_showText.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.626866 rgba(255, 232, 185, 255));\n"
"border-radius:20px;\n"
"color: rgb(0, 0, 0);")
        self.feat_showText.setObjectName("feat_showText")
        self.verticalLayout_5.addWidget(self.feat_showText)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem5 = QtWidgets.QSpacerItem(149, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.btn_editor = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_editor.sizePolicy().hasHeightForWidth())
        self.btn_editor.setSizePolicy(sizePolicy)
        self.btn_editor.setMinimumSize(QtCore.QSize(170, 35))
        self.btn_editor.setMaximumSize(QtCore.QSize(170, 35))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_editor.setFont(font)
        self.btn_editor.setStyleSheet("border-radius:7px")
        self.btn_editor.setObjectName("btn_editor")
        self.horizontalLayout_9.addWidget(self.btn_editor)
        self.btn_addpicture = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.btn_addpicture.setMinimumSize(QtCore.QSize(170, 35))
        self.btn_addpicture.setMaximumSize(QtCore.QSize(170, 35))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_addpicture.setFont(font)
        self.btn_addpicture.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color:rgb(255, 170, 0);\n"
"border-radius:7px")
        self.btn_addpicture.setObjectName("btn_addpicture")
        self.horizontalLayout_9.addWidget(self.btn_addpicture)
        spacerItem6 = QtWidgets.QSpacerItem(149, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.wgt_showPicture = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.wgt_showPicture.setMinimumSize(QtCore.QSize(0, 500))
        self.wgt_showPicture.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.626866 rgba(255, 232, 185, 255));\n"
"border-radius:20px;\n"
"color: rgb(0, 0, 0);")
        self.wgt_showPicture.setObjectName("wgt_showPicture")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.wgt_showPicture)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.btn_pre_pic = QtWidgets.QPushButton(self.wgt_showPicture)
        self.btn_pre_pic.setMinimumSize(QtCore.QSize(30, 500))
        self.btn_pre_pic.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btn_pre_pic.setStyleSheet("border-radius:10px;")
        self.btn_pre_pic.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/image/images/向左.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_pre_pic.setIcon(icon1)
        self.btn_pre_pic.setObjectName("btn_pre_pic")
        self.horizontalLayout_13.addWidget(self.btn_pre_pic)
        self.label_Picture = QtWidgets.QLabel(self.wgt_showPicture)
        self.label_Picture.setMinimumSize(QtCore.QSize(18, 0))
        self.label_Picture.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.626866 rgba(255, 232, 185, 255));")
        self.label_Picture.setText("")
        self.label_Picture.setObjectName("label_Picture")
        self.horizontalLayout_13.addWidget(self.label_Picture)
        self.btn_next_pic = QtWidgets.QPushButton(self.wgt_showPicture)
        self.btn_next_pic.setMinimumSize(QtCore.QSize(30, 500))
        self.btn_next_pic.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btn_next_pic.setStyleSheet("border-radius:10px;")
        self.btn_next_pic.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/image/images/向右.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_next_pic.setIcon(icon2)
        self.btn_next_pic.setObjectName("btn_next_pic")
        self.horizontalLayout_13.addWidget(self.btn_next_pic)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_13)
        self.verticalLayout_5.addWidget(self.wgt_showPicture)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.btn_addVideo = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.btn_addVideo.setMinimumSize(QtCore.QSize(35, 35))
        self.btn_addVideo.setMaximumSize(QtCore.QSize(45, 45))
        self.btn_addVideo.setStyleSheet("image: url(:/images/images/icon_zengjia.png);\n"
"border:none;\n"
"color:none;\n"
"background-color:none;")
        self.btn_addVideo.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/image/images/添加_填充.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_addVideo.setIcon(icon3)
        self.btn_addVideo.setIconSize(QtCore.QSize(45, 45))
        self.btn_addVideo.setObjectName("btn_addVideo")
        self.horizontalLayout_7.addWidget(self.btn_addVideo)
        self.btn_playVideo = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.btn_playVideo.setMinimumSize(QtCore.QSize(150, 70))
        self.btn_playVideo.setMaximumSize(QtCore.QSize(150, 70))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_playVideo.setFont(font)
        self.btn_playVideo.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color:rgb(255, 170, 0);\n"
"border-radius:7px")
        self.btn_playVideo.setObjectName("btn_playVideo")
        self.horizontalLayout_7.addWidget(self.btn_playVideo)
        self.btn_addMusic = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.btn_addMusic.setMinimumSize(QtCore.QSize(35, 35))
        self.btn_addMusic.setMaximumSize(QtCore.QSize(45, 45))
        self.btn_addMusic.setStyleSheet("image: url(:/images/images/icon_zengjia.png);\n"
"border:none;\n"
"color:none;\n"
"background-color:none;")
        self.btn_addMusic.setText("")
        self.btn_addMusic.setIcon(icon3)
        self.btn_addMusic.setIconSize(QtCore.QSize(45, 45))
        self.btn_addMusic.setObjectName("btn_addMusic")
        self.horizontalLayout_7.addWidget(self.btn_addMusic)
        self.btn_playMusic = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.btn_playMusic.setMinimumSize(QtCore.QSize(150, 70))
        self.btn_playMusic.setMaximumSize(QtCore.QSize(150, 70))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_playMusic.setFont(font)
        self.btn_playMusic.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color:rgb(255, 170, 0);\n"
"border-radius:7px")
        self.btn_playMusic.setObjectName("btn_playMusic")
        self.horizontalLayout_7.addWidget(self.btn_playMusic)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.verticalLayout_5.setStretch(2, 1)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.addWidget(self.scrollArea)
        self.dockWidget_feature.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_feature)
        self.dockWidget_RouteGuide = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(70)
        sizePolicy.setHeightForWidth(self.dockWidget_RouteGuide.sizePolicy().hasHeightForWidth())
        self.dockWidget_RouteGuide.setSizePolicy(sizePolicy)
        self.dockWidget_RouteGuide.setMinimumSize(QtCore.QSize(500, 400))
        self.dockWidget_RouteGuide.setStyleSheet("QDockWidget{background-color: rgb(79, 79, 79);border-radius:20px;color: rgb(218, 218, 218);}\n"
"QLabel{color: rgb(218, 218, 218);}\n"
"\n"
"\n"
"QPushButton{\n"
"    border-radius: 7px;\n"
"    background-color: rgb(0, 0, 0);\n"
"    border: 2px solid  rgb(236, 236, 236);\n"
"    color: rgb(255, 170, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    border: 4px double rgb(255, 170, 0);\n"
"    color: rgb(255, 170, 0)\n"
"}\n"
"QPushButton:checked{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color:  rgb(255, 170, 0);\n"
"    \n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.dockWidget_RouteGuide.setFloating(True)
        self.dockWidget_RouteGuide.setObjectName("dockWidget_RouteGuide")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.dockWidgetContents_3)
        self.scrollArea_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:20px;")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 478, 862))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label.setStyleSheet("font: 16pt \"黑体\";")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.feat_name_D2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.feat_name_D2.setStyleSheet("font: 16pt \"黑体\";")
        self.feat_name_D2.setObjectName("feat_name_D2")
        self.horizontalLayout_2.addWidget(self.feat_name_D2)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.verticalLayout_11.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_10.addWidget(self.label_5)
        self.dateEdit = QtWidgets.QDateEdit(self.scrollAreaWidgetContents_3)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_10.addWidget(self.dateEdit)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem10)
        self.verticalLayout_11.addLayout(self.horizontalLayout_10)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lineEdit_start = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_start.setMinimumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_start.setFont(font)
        self.lineEdit_start.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.626866 rgba(255, 232, 185, 255));\n"
"border-radius:7px;\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_start.setObjectName("lineEdit_start")
        self.horizontalLayout_12.addWidget(self.lineEdit_start)
        self.btn_changeDire = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_changeDire.setMinimumSize(QtCore.QSize(45, 45))
        self.btn_changeDire.setMaximumSize(QtCore.QSize(45, 45))
        self.btn_changeDire.setBaseSize(QtCore.QSize(45, 45))
        self.btn_changeDire.setStyleSheet("\n"
"QPushButton{border:none}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.btn_changeDire.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/image/images/交换.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_changeDire.setIcon(icon4)
        self.btn_changeDire.setIconSize(QtCore.QSize(45, 45))
        self.btn_changeDire.setObjectName("btn_changeDire")
        self.horizontalLayout_12.addWidget(self.btn_changeDire)
        self.lineEdit_stop = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_stop.setMinimumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_stop.setFont(font)
        self.lineEdit_stop.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.626866 rgba(255, 232, 185, 255));\n"
"border-radius:7px;\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_stop.setObjectName("lineEdit_stop")
        self.horizontalLayout_12.addWidget(self.lineEdit_stop)
        self.verticalLayout_12.addLayout(self.horizontalLayout_12)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btn_routeGuide_car = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_routeGuide_car.setMinimumSize(QtCore.QSize(100, 35))
        self.btn_routeGuide_car.setMaximumSize(QtCore.QSize(10000, 35))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_routeGuide_car.setFont(font)
        self.btn_routeGuide_car.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color:rgb(255, 170, 0);\n"
"border-radius:7px")
        self.btn_routeGuide_car.setObjectName("btn_routeGuide_car")
        self.gridLayout.addWidget(self.btn_routeGuide_car, 0, 0, 1, 1)
        self.btn_routeGuide_bike = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_routeGuide_bike.setMinimumSize(QtCore.QSize(100, 35))
        self.btn_routeGuide_bike.setMaximumSize(QtCore.QSize(10000, 35))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_routeGuide_bike.setFont(font)
        self.btn_routeGuide_bike.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color:rgb(255, 170, 0);\n"
"border-radius:7px")
        self.btn_routeGuide_bike.setObjectName("btn_routeGuide_bike")
        self.gridLayout.addWidget(self.btn_routeGuide_bike, 1, 0, 1, 1)
        self.btn_routeGuide_bus = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_routeGuide_bus.setMinimumSize(QtCore.QSize(100, 35))
        self.btn_routeGuide_bus.setMaximumSize(QtCore.QSize(10000, 35))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_routeGuide_bus.setFont(font)
        self.btn_routeGuide_bus.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color:rgb(255, 170, 0);\n"
"border-radius:7px")
        self.btn_routeGuide_bus.setObjectName("btn_routeGuide_bus")
        self.gridLayout.addWidget(self.btn_routeGuide_bus, 1, 1, 1, 1)
        self.btn_routeGuide_walk = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_routeGuide_walk.setMinimumSize(QtCore.QSize(100, 35))
        self.btn_routeGuide_walk.setMaximumSize(QtCore.QSize(10000, 35))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_routeGuide_walk.setFont(font)
        self.btn_routeGuide_walk.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color:rgb(255, 170, 0);\n"
"border-radius:7px")
        self.btn_routeGuide_walk.setObjectName("btn_routeGuide_walk")
        self.gridLayout.addWidget(self.btn_routeGuide_walk, 0, 1, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout)
        self.route_text = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.route_text.setFont(font)
        self.route_text.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.626866 rgba(255, 232, 185, 255));\n"
"border-radius:20px;\n"
"color: rgb(0, 0, 0);")
        self.route_text.setObjectName("route_text")
        self.verticalLayout_12.addWidget(self.route_text)
        self.verticalLayout_14.addLayout(self.verticalLayout_12)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_13.addWidget(self.scrollArea_2)
        self.dockWidget_RouteGuide.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_RouteGuide)
        self.actionzoom_in = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/image/images/suoxiao.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionzoom_in.setIcon(icon5)
        self.actionzoom_in.setObjectName("actionzoom_in")
        self.actionzoom_out = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/image/images/fangda.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionzoom_out.setIcon(icon6)
        self.actionzoom_out.setObjectName("actionzoom_out")
        self.actionmeasure_distance = QtWidgets.QAction(MainWindow)
        self.actionmeasure_distance.setCheckable(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/image/images/distance.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionmeasure_distance.setIcon(icon7)
        self.actionmeasure_distance.setObjectName("actionmeasure_distance")
        self.actionopen_file = QtWidgets.QAction(MainWindow)
        self.actionopen_file.setCheckable(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/image/images/24gf-folderOpen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionopen_file.setIcon(icon8)
        self.actionopen_file.setIconVisibleInMenu(True)
        self.actionopen_file.setObjectName("actionopen_file")
        self.actionpan = QtWidgets.QAction(MainWindow)
        self.actionpan.setCheckable(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/image/images/move.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionpan.setIcon(icon9)
        self.actionpan.setObjectName("actionpan")
        self.actionidentify = QtWidgets.QAction(MainWindow)
        self.actionidentify.setCheckable(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/image/images/select.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionidentify.setIcon(icon10)
        self.actionidentify.setObjectName("actionidentify")
        self.actionmap_overview = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/image/images/地图插图.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionmap_overview.setIcon(icon11)
        self.actionmap_overview.setObjectName("actionmap_overview")
        self.actionclear_draw = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/image/images/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionclear_draw.setIcon(icon12)
        self.actionclear_draw.setObjectName("actionclear_draw")
        self.actionfeatureInfo = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/image/images/overview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionfeatureInfo.setIcon(icon13)
        self.actionfeatureInfo.setObjectName("actionfeatureInfo")
        self.actionAddRaster = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/image/images/icon_zengjia.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAddRaster.setIcon(icon14)
        self.actionAddRaster.setObjectName("actionAddRaster")
        self.actionRouteGuide = QtWidgets.QAction(MainWindow)
        self.actionRouteGuide.setIcon(icon11)
        self.actionRouteGuide.setObjectName("actionRouteGuide")
        self.menu_2.addAction(self.actionfeatureInfo)
        self.menu_2.addAction(self.actionRouteGuide)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "时光GIS"))
        self.startlineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>初始地点</p></body></html>"))
        self.startlineEdit.setPlaceholderText(_translate("MainWindow", "起始点"))
        self.endlineEdit.setPlaceholderText(_translate("MainWindow", "搜索地点"))
        self.searchButton.setText(_translate("MainWindow", "查询"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_folium), _translate("MainWindow", "folium"))
        self.menu.setTitle(_translate("MainWindow", "开始"))
        self.menu_2.setTitle(_translate("MainWindow", "视图"))
        self.dockWidget_feature.setWindowTitle(_translate("MainWindow", "地点信息"))
        self.feat_name_D1.setText(_translate("MainWindow", "地名"))
        self.label_7.setText(_translate("MainWindow", "坐标信息："))
        self.btn_addPoint.setText(_translate("MainWindow", "标记！"))
        self.label_3.setText(_translate("MainWindow", "游览日期 ："))
        self.btn_update.setText(_translate("MainWindow", "更新标记"))
        self.btn_routeGuide.setText(_translate("MainWindow", "规划路线"))
        self.feat_showText.setPlaceholderText(_translate("MainWindow", "点击编辑文字开始记录在这里的时光记忆叭~"))
        self.btn_editor.setText(_translate("MainWindow", "编辑文字"))
        self.btn_addpicture.setText(_translate("MainWindow", "添加照片"))
        self.btn_playVideo.setText(_translate("MainWindow", "查看视频"))
        self.btn_playMusic.setText(_translate("MainWindow", "查看音频"))
        self.dockWidget_RouteGuide.setWindowTitle(_translate("MainWindow", "路线规划"))
        self.label.setText(_translate("MainWindow", "准备到:"))
        self.feat_name_D2.setText(_translate("MainWindow", "地名"))
        self.label_5.setText(_translate("MainWindow", "游览日期 ："))
        self.lineEdit_start.setPlaceholderText(_translate("MainWindow", "起点："))
        self.lineEdit_stop.setPlaceholderText(_translate("MainWindow", "终点："))
        self.btn_routeGuide_car.setText(_translate("MainWindow", "驾车"))
        self.btn_routeGuide_bike.setText(_translate("MainWindow", "骑行"))
        self.btn_routeGuide_bus.setText(_translate("MainWindow", "公交交通"))
        self.btn_routeGuide_walk.setText(_translate("MainWindow", "步行"))
        self.route_text.setPlaceholderText(_translate("MainWindow", "点击出行方式获得路线规划~"))
        self.actionzoom_in.setText(_translate("MainWindow", "缩小"))
        self.actionzoom_in.setToolTip(_translate("MainWindow", "缩小"))
        self.actionzoom_out.setText(_translate("MainWindow", "放大"))
        self.actionzoom_out.setToolTip(_translate("MainWindow", "放大"))
        self.actionmeasure_distance.setText(_translate("MainWindow", "测算距离"))
        self.actionmeasure_distance.setToolTip(_translate("MainWindow", "测算距离"))
        self.actionopen_file.setText(_translate("MainWindow", "打开shp文件"))
        self.actionopen_file.setToolTip(_translate("MainWindow", "添加图层"))
        self.actionopen_file.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionpan.setText(_translate("MainWindow", "平移地图"))
        self.actionpan.setToolTip(_translate("MainWindow", "平移地图"))
        self.actionidentify.setText(_translate("MainWindow", "选择"))
        self.actionidentify.setToolTip(_translate("MainWindow", "选择"))
        self.actionmap_overview.setText(_translate("MainWindow", "地图概览"))
        self.actionmap_overview.setToolTip(_translate("MainWindow", "地图概览"))
        self.actionclear_draw.setText(_translate("MainWindow", "清除绘制"))
        self.actionclear_draw.setToolTip(_translate("MainWindow", "清除绘制"))
        self.actionfeatureInfo.setText(_translate("MainWindow", "地点信息"))
        self.actionAddRaster.setText(_translate("MainWindow", "加载栅格"))
        self.actionAddRaster.setToolTip(_translate("MainWindow", "添加矢量图层"))
        self.actionRouteGuide.setText(_translate("MainWindow", "路线规划"))
from PyQt5 import QtWebEngineWidgets
import resourse_rc
