# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MusicPlayer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MusicPlayer(object):
    def setupUi(self, MusicPlayer):
        MusicPlayer.setObjectName("MusicPlayer")
        MusicPlayer.resize(878, 449)
        MusicPlayer.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MusicPlayer)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 20, 701, 361))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:30px;\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.btn_close = QtWidgets.QPushButton(self.centralwidget)
        self.btn_close.setGeometry(QtCore.QRect(740, 40, 21, 21))
        self.btn_close.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:Pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.btn_close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/images/叉.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon)
        self.btn_close.setObjectName("btn_close")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(690, 30, 31, 31))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:Pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/image/images/缩小.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.btn_play = QtWidgets.QPushButton(self.centralwidget)
        self.btn_play.setGeometry(QtCore.QRect(500, 220, 61, 51))
        self.btn_play.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:Pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.btn_play.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/image/images/播放.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_play.setIcon(icon2)
        self.btn_play.setIconSize(QtCore.QSize(55, 55))
        self.btn_play.setObjectName("btn_play")
        self.btn_next = QtWidgets.QPushButton(self.centralwidget)
        self.btn_next.setGeometry(QtCore.QRect(610, 220, 61, 51))
        self.btn_next.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:Pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.btn_next.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/image/images/下一首2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_next.setIcon(icon3)
        self.btn_next.setIconSize(QtCore.QSize(55, 55))
        self.btn_next.setObjectName("btn_next")
        self.btn_pause = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pause.setGeometry(QtCore.QRect(370, 220, 61, 51))
        self.btn_pause.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:Pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.btn_pause.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/image/images/暂停.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_pause.setIcon(icon4)
        self.btn_pause.setIconSize(QtCore.QSize(55, 55))
        self.btn_pause.setObjectName("btn_pause")
        self.btn_file = QtWidgets.QPushButton(self.centralwidget)
        self.btn_file.setGeometry(QtCore.QRect(130, 30, 61, 51))
        self.btn_file.setStyleSheet("border-image: url(:/image/images/24gf-playlistMusic2.png);")
        self.btn_file.setText("")
        self.btn_file.setObjectName("btn_file")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 180, 611, 131))
        self.label_2.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-radius:30px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 10, 721, 381))
        self.label_3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:30px;\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(160, 140, 441, 31))
        self.textBrowser.setStyleSheet("border:none;\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.btn_pre = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pre.setGeometry(QtCore.QRect(240, 220, 61, 51))
        self.btn_pre.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:Pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.btn_pre.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/image/images/上一首.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_pre.setIcon(icon5)
        self.btn_pre.setIconSize(QtCore.QSize(55, 55))
        self.btn_pre.setObjectName("btn_pre")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(170, 330, 571, 22))
        self.horizontalSlider.setStyleSheet("/*horizontal ：水平QSlider*/\n"
"QSlider::groove:horizontal {\n"
"border: 0px solid #bbb;\n"
"}\n"
"\n"
"/*1.滑动过的槽设计参数*/\n"
"QSlider::sub-page:horizontal {\n"
" /*槽颜色*/\n"
"background: rgb(255, 170, 0);\n"
" /*外环区域倒圆角度*/\n"
"border-radius: 2px;\n"
" /*上遮住区域高度*/\n"
"margin-top:8px;\n"
" /*下遮住区域高度*/\n"
"margin-bottom:8px;\n"
"/*width在这里无效，不写即可*/\n"
"}\n"
"\n"
"/*2.未滑动过的槽设计参数*/\n"
"QSlider::add-page:horizontal {\n"
"/*槽颜色*/\n"
"background: rgb(255,255, 255);\n"
"/*外环大小0px就是不显示，默认也是0*/\n"
"border: 0px solid #777;\n"
"/*外环区域倒圆角度*/\n"
"border-radius: 2px;\n"
" /*上遮住区域高度*/\n"
"margin-top:9px;\n"
" /*下遮住区域高度*/\n"
"margin-bottom:9px;\n"
"}\n"
" \n"
"/*3.平时滑动的滑块设计参数*/\n"
"QSlider::handle:horizontal {\n"
"/*滑块颜色*/\n"
"background: rgb(193,204,208);\n"
"/*滑块的宽度*/\n"
"width: 5px;\n"
"/*滑块外环为1px，再加颜色*/\n"
"border: 1px solid rgb(193,204,208);\n"
" /*滑块外环倒圆角度*/\n"
"border-radius: 2px; \n"
" /*上遮住区域高度*/\n"
"margin-top:6px;\n"
" /*下遮住区域高度*/\n"
"margin-bottom:6px;\n"
"}\n"
"\n"
"/*4.手动拉动时显示的滑块设计参数*/\n"
"QSlider::handle:horizontal:hover {\n"
"/*滑块颜色*/\n"
"background: rgb(193,204,208);\n"
"/*滑块的宽度*/\n"
"width: 10px;\n"
"/*滑块外环为1px，再加颜色*/\n"
"border: 1px solid rgb(193,204,208);\n"
" /*滑块外环倒圆角度*/\n"
"border-radius: 5px; \n"
" /*上遮住区域高度*/\n"
"margin-top:4px;\n"
" /*下遮住区域高度*/\n"
"margin-bottom:4px;\n"
"}\n"
"")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(90, 10, 721, 301))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(160, 110, 72, 15))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(210, 40, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.frame.raise_()
        self.label_3.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.btn_close.raise_()
        self.pushButton_2.raise_()
        self.btn_play.raise_()
        self.btn_next.raise_()
        self.btn_pause.raise_()
        self.btn_file.raise_()
        self.textBrowser.raise_()
        self.btn_pre.raise_()
        self.horizontalSlider.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        MusicPlayer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MusicPlayer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 878, 26))
        self.menubar.setObjectName("menubar")
        MusicPlayer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MusicPlayer)
        self.statusbar.setObjectName("statusbar")
        MusicPlayer.setStatusBar(self.statusbar)

        self.retranslateUi(MusicPlayer)
        self.btn_close.clicked.connect(MusicPlayer.close)
        self.pushButton_2.clicked.connect(MusicPlayer.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MusicPlayer)

    def retranslateUi(self, MusicPlayer):
        _translate = QtCore.QCoreApplication.translate
        MusicPlayer.setWindowTitle(_translate("MusicPlayer", "MainWindow"))
        self.textBrowser.setPlaceholderText(_translate("MusicPlayer", "暂无"))
        self.label_4.setText(_translate("MusicPlayer", "正在播放："))
        self.label_5.setText(_translate("MusicPlayer", "当前日期和地点的音频"))
import resourse_rc
