# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_TextEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(966, 732)
        MainWindow.setStyleSheet("QPushBoton:checked{\n"
"    padding-top:4px;\n"
"    padding-left:4px;\n"
"\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 921, 671))
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:20px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(50, 40, 31, 31))
        self.btn_save.setStyleSheet("border-image: url(:/image/images/wenbenbianji.png);")
        self.btn_save.setText("")
        self.btn_save.setObjectName("btn_save")
        self.btn_bold = QtWidgets.QPushButton(self.centralwidget)
        self.btn_bold.setGeometry(QtCore.QRect(370, 40, 31, 31))
        self.btn_bold.setStyleSheet("border-image: url(:/image/images/fuwenbenbianjiqi_jiacu.png);")
        self.btn_bold.setText("")
        self.btn_bold.setObjectName("btn_bold")
        self.btn_color = QtWidgets.QPushButton(self.centralwidget)
        self.btn_color.setGeometry(QtCore.QRect(410, 40, 31, 31))
        self.btn_color.setStyleSheet("border-image: url(:/image/images/fuwenbenbianjiqi_zitiyanse.png);")
        self.btn_color.setText("")
        self.btn_color.setObjectName("btn_color")
        self.btn_underline = QtWidgets.QPushButton(self.centralwidget)
        self.btn_underline.setGeometry(QtCore.QRect(450, 40, 31, 31))
        self.btn_underline.setStyleSheet("border-image: url(:/image/images/fuwenbenbianjiqi_xiahuaxian.png);")
        self.btn_underline.setText("")
        self.btn_underline.setObjectName("btn_underline")
        self.btn_cut = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cut.setGeometry(QtCore.QRect(530, 40, 31, 31))
        self.btn_cut.setStyleSheet("border-image: url(:/image/images/jianqiewenjian.png);")
        self.btn_cut.setText("")
        self.btn_cut.setObjectName("btn_cut")
        self.btn_italy = QtWidgets.QPushButton(self.centralwidget)
        self.btn_italy.setGeometry(QtCore.QRect(490, 40, 31, 31))
        self.btn_italy.setStyleSheet("border-image: url(:/image/images/fuwenbenbianjiqi_ziti.png);")
        self.btn_italy.setText("")
        self.btn_italy.setObjectName("btn_italy")
        self.btn_save2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save2.setGeometry(QtCore.QRect(810, 510, 93, 28))
        self.btn_save2.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-radius:4px;\n"
"")
        self.btn_save2.setObjectName("btn_save2")
        self.btn_clear = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear.setGeometry(QtCore.QRect(810, 560, 93, 28))
        self.btn_clear.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-radius:4px;")
        self.btn_clear.setObjectName("btn_clear")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(810, 610, 93, 28))
        self.pushButton_9.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-radius:4px;")
        self.pushButton_9.setObjectName("pushButton_9")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(30, 90, 751, 571))
        self.textEdit.setStyleSheet("font: 18pt \"Arial\";\n"
"border-radius:20px;")
        self.textEdit.setObjectName("textEdit")
        self.fontComboBox = QtWidgets.QFontComboBox(self.centralwidget)
        self.fontComboBox.setGeometry(QtCore.QRect(100, 40, 151, 31))
        self.fontComboBox.setStyleSheet("\n"
"border-radius:4px;")
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.fontComboBox.setCurrentFont(font)
        self.fontComboBox.setObjectName("fontComboBox")
        self.spinBox_fontsize = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_fontsize.setGeometry(QtCore.QRect(270, 40, 91, 31))
        self.spinBox_fontsize.setStyleSheet("border-radius:4px;")
        self.spinBox_fontsize.setMinimum(18)
        self.spinBox_fontsize.setMaximum(64)
        self.spinBox_fontsize.setSingleStep(2)
        self.spinBox_fontsize.setObjectName("spinBox_fontsize")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(790, 270, 121, 31))
        self.dateEdit.setObjectName("dateEdit")
        self.btn_select_date = QtWidgets.QPushButton(self.centralwidget)
        self.btn_select_date.setGeometry(QtCore.QRect(790, 230, 121, 28))
        self.btn_select_date.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-radius:4px;\n"
"")
        self.btn_select_date.setObjectName("btn_select_date")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(872, 30, 31, 28))
        self.pushButton_12.setStyleSheet("border-image: url(:/image/images/关闭26.png);")
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(640, 520, 151, 151))
        self.label_2.setStyleSheet("border-image: url(:/image/images/看_.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 966, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_9.clicked.connect(MainWindow.close)
        self.pushButton_12.clicked.connect(MainWindow.close)
        self.btn_underline.clicked['bool'].connect(self.textEdit.setFontUnderline)
        self.btn_bold.clicked['bool'].connect(self.textEdit.setFocus)
        self.btn_italy.clicked['bool'].connect(self.textEdit.setFontItalic)
        self.btn_cut.clicked.connect(self.textEdit.cut)
        self.btn_clear.clicked.connect(self.textEdit.clear)
        self.spinBox_fontsize.valueChanged['int'].connect(self.textEdit.setFontWeight)
        self.fontComboBox.currentFontChanged['QFont'].connect(self.textEdit.setCurrentFont)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_save.setToolTip(_translate("MainWindow", "<html><head/><body><p>保存</p></body></html>"))
        self.btn_underline.setToolTip(_translate("MainWindow", "<html><head/><body><p>下划线</p></body></html>"))
        self.btn_italy.setToolTip(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">斜体</p></body></html>"))
        self.btn_save2.setText(_translate("MainWindow", "保存"))
        self.btn_clear.setText(_translate("MainWindow", "清空"))
        self.pushButton_9.setText(_translate("MainWindow", "退出"))
        self.btn_select_date.setText(_translate("MainWindow", "设置日期"))
import resourse_rc
