# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_VideoPlayer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VideoPlayer(object):
    def setupUi(self, VideoPlayer):
        VideoPlayer.setObjectName("VideoPlayer")
        VideoPlayer.resize(982, 737)
        VideoPlayer.setStyleSheet("QPushButton{\n"
"    borde:none\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}\n"
"QMainWindow{background-color: rgb(0, 0, 0);}\n"
"")
        self.centralwidget = QtWidgets.QWidget(VideoPlayer)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 981, 721))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.btn_close = QtWidgets.QPushButton(self.centralwidget)
        self.btn_close.setGeometry(QtCore.QRect(930, 20, 21, 21))
        self.btn_close.setStyleSheet("border-image: url(:/image/images/叉.png);")
        self.btn_close.setText("")
        self.btn_close.setObjectName("btn_close")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(880, 10, 31, 31))
        self.pushButton_2.setStyleSheet("border-image: url(:/image/images/缩小.png);")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 640, 521, 71))
        self.label_2.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-radius:30px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.btn_next = QtWidgets.QPushButton(self.centralwidget)
        self.btn_next.setGeometry(QtCore.QRect(630, 650, 61, 51))
        self.btn_next.setStyleSheet("border:none;")
        self.btn_next.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/images/下一首2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_next.setIcon(icon)
        self.btn_next.setIconSize(QtCore.QSize(55, 55))
        self.btn_next.setObjectName("btn_next")
        self.btn_pause = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pause.setGeometry(QtCore.QRect(410, 650, 61, 51))
        self.btn_pause.setStyleSheet("border:none;")
        self.btn_pause.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/image/images/暂停.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_pause.setIcon(icon1)
        self.btn_pause.setIconSize(QtCore.QSize(55, 55))
        self.btn_pause.setObjectName("btn_pause")
        self.btn_play = QtWidgets.QPushButton(self.centralwidget)
        self.btn_play.setGeometry(QtCore.QRect(520, 650, 61, 51))
        self.btn_play.setStyleSheet("border:none;")
        self.btn_play.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/image/images/播放.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_play.setIcon(icon2)
        self.btn_play.setIconSize(QtCore.QSize(55, 55))
        self.btn_play.setObjectName("btn_play")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(120, 600, 741, 22))
        self.horizontalSlider.setStyleSheet("/*horizontal ：水平QSlider*/\n"
"QSlider::groove:horizontal {\n"
"border: 0px solid #bbb;\n"
"}\n"
"\n"
"/*1.滑动过的槽设计参数*/\n"
"QSlider::sub-page:horizontal {\n"
" /*槽颜色*/\n"
"background: rgb(255, 170, 0);\n"
" /*外环区域倒圆角度*/\n"
"border-radius: 2px;\n"
" /*上遮住区域高度*/\n"
"margin-top:8px;\n"
" /*下遮住区域高度*/\n"
"margin-bottom:8px;\n"
"/*width在这里无效，不写即可*/\n"
"}\n"
"\n"
"/*2.未滑动过的槽设计参数*/\n"
"QSlider::add-page:horizontal {\n"
"/*槽颜色*/\n"
"background: rgb(255,255, 255);\n"
"/*外环大小0px就是不显示，默认也是0*/\n"
"border: 0px solid #777;\n"
"/*外环区域倒圆角度*/\n"
"border-radius: 2px;\n"
" /*上遮住区域高度*/\n"
"margin-top:9px;\n"
" /*下遮住区域高度*/\n"
"margin-bottom:9px;\n"
"}\n"
" \n"
"/*3.平时滑动的滑块设计参数*/\n"
"QSlider::handle:horizontal {\n"
"/*滑块颜色*/\n"
"background: rgb(193,204,208);\n"
"/*滑块的宽度*/\n"
"width: 5px;\n"
"/*滑块外环为1px，再加颜色*/\n"
"border: 1px solid rgb(193,204,208);\n"
" /*滑块外环倒圆角度*/\n"
"border-radius: 2px; \n"
" /*上遮住区域高度*/\n"
"margin-top:6px;\n"
" /*下遮住区域高度*/\n"
"margin-bottom:6px;\n"
"}\n"
"\n"
"/*4.手动拉动时显示的滑块设计参数*/\n"
"QSlider::handle:horizontal:hover {\n"
"/*滑块颜色*/\n"
"background: rgb(193,204,208);\n"
"/*滑块的宽度*/\n"
"width: 10px;\n"
"/*滑块外环为1px，再加颜色*/\n"
"border: 1px solid rgb(193,204,208);\n"
" /*滑块外环倒圆角度*/\n"
"border-radius: 5px; \n"
" /*上遮住区域高度*/\n"
"margin-top:4px;\n"
" /*下遮住区域高度*/\n"
"margin-bottom:4px;\n"
"}\n"
"")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 961, 581))
        self.label_3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.wgt_videoplayer = QVideoWidget(self.centralwidget)
        self.wgt_videoplayer.setGeometry(QtCore.QRect(30, 60, 921, 521))
        self.wgt_videoplayer.setStyleSheet("border-radius:30px;")
        self.wgt_videoplayer.setObjectName("wgt_videoplayer")
        self.btn_file = QtWidgets.QPushButton(self.centralwidget)
        self.btn_file.setGeometry(QtCore.QRect(30, 0, 51, 41))
        self.btn_file.setStyleSheet("border:none;")
        self.btn_file.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/image/images/视频列表-02.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_file.setIcon(icon3)
        self.btn_file.setIconSize(QtCore.QSize(45, 45))
        self.btn_file.setObjectName("btn_file")
        self.btn_pre = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pre.setGeometry(QtCore.QRect(310, 650, 61, 51))
        self.btn_pre.setStyleSheet("border:none;")
        self.btn_pre.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/image/images/上一首.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_pre.setIcon(icon4)
        self.btn_pre.setIconSize(QtCore.QSize(55, 55))
        self.btn_pre.setObjectName("btn_pre")
        self.timeDisplay = QtWidgets.QTextBrowser(self.centralwidget)
        self.timeDisplay.setGeometry(QtCore.QRect(870, 590, 91, 31))
        self.timeDisplay.setStyleSheet("border:none;\n"
"font: 10pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.timeDisplay.setObjectName("timeDisplay")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(100, 10, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.label.raise_()
        self.label_3.raise_()
        self.btn_close.raise_()
        self.pushButton_2.raise_()
        self.label_2.raise_()
        self.btn_next.raise_()
        self.btn_pause.raise_()
        self.btn_play.raise_()
        self.horizontalSlider.raise_()
        self.wgt_videoplayer.raise_()
        self.btn_file.raise_()
        self.btn_pre.raise_()
        self.timeDisplay.raise_()
        self.label_name.raise_()
        VideoPlayer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VideoPlayer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 982, 26))
        self.menubar.setObjectName("menubar")
        VideoPlayer.setMenuBar(self.menubar)

        self.retranslateUi(VideoPlayer)
        self.btn_close.clicked.connect(VideoPlayer.close)
        self.pushButton_2.clicked.connect(VideoPlayer.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(VideoPlayer)

    def retranslateUi(self, VideoPlayer):
        _translate = QtCore.QCoreApplication.translate
        VideoPlayer.setWindowTitle(_translate("VideoPlayer", "MainWindow"))
        self.timeDisplay.setHtml(_translate("VideoPlayer", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_name.setText(_translate("VideoPlayer", "当前视频名称"))
from PyQt5.QtMultimediaWidgets import QVideoWidget
import resourse_rc
